#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop and disable service
        systemctl stop accel-exporter.service || true
        systemctl disable accel-exporter.service || true
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0